title = "Precious My Life Story"
baseURL = "https://jolly-kalam-6732c8.netlify.app"
languageCode = "en-us"
theme = "ananke"
themesDir = "themes"

MetaDataFormat = "yaml"
DefaultContentLanguage = "en"
SectionPagesMenu = "main"
Paginate = 3 # this is set low for demonstrating with dummy content. Set to a higher number
googleAnalytics = ""
enableRobotsTXT = true

[sitemap]
  changefreq = "monthly"
  priority = 0.5
  filename = "sitemap.xml"

[params]
  favicon = ""
  site_logo ="/logo.png" 
  description = "The last theme you'll ever need. Maybe."
  facebook = ""
  twitter = ""
  instagram = "https://www.instagram.com/cookingwithsach/"
  youtube = ""
  github = "https://github.com/pi-recious"
  gitlab = ""
  linkedin = "https://www.linkedin.com/in/preciousadewunmi/"
  mastodon = ""
  slack = ""
  stackoverflow = ""
  rss = ""
  body_classes = "avenir bg-washed-red"
  # choose a background color from any on this page: http://tachyons.io/docs/themes/skins/ and preface it with "bg-"
  background_color_class = "bg-pink"
  featured_image = "/ACS_Smile.jpg"
  recent_posts_number = 2

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      unsafe = true